import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_outdt",
        field: "outdt",
        caption: "판매년도",
        width: 120,
      },
      {
        id: "col_amt01",
        field: "amt01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_amt02",
        field: "amt02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_amt03",
        field: "amt03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_amt04",
        field: "amt04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_amt05",
        field: "amt05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_amt06",
        field: "amt06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_amt07",
        field: "amt07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_amt08",
        field: "amt08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_amt09",
        field: "amt09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_amt10",
        field: "amt10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_amt11",
        field: "amt11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_amt12",
        field: "amt12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "총계",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_acntnm",
        field: "acntnm",
        caption: "계정과목",
        width: 120,
      },
      {
        id: "col_amt011",
        field: "amt01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_amt021",
        field: "amt02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_amt031",
        field: "amt03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_amt041",
        field: "amt04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_amt051",
        field: "amt05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_amt061",
        field: "amt06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_amt071",
        field: "amt07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_amt081",
        field: "amt08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_amt091",
        field: "amt09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_amt101",
        field: "amt10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_amt111",
        field: "amt11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_amt121",
        field: "amt12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_totamt2",
        field: "totamt",
        caption: "총계",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_acntnm2",
        field: "acntnm",
        caption: "계정과목",
        width: 120,
      },
      {
        id: "col_amt012",
        field: "amt01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_amt022",
        field: "amt02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_amt032",
        field: "amt03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_amt042",
        field: "amt04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_amt052",
        field: "amt05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_amt062",
        field: "amt06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_amt072",
        field: "amt07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_amt082",
        field: "amt08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_amt092",
        field: "amt09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_amt102",
        field: "amt10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_amt112",
        field: "amt11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_amt122",
        field: "amt12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_totamt3",
        field: "totamt",
        caption: "총계",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_acntdt",
        field: "acntdt",
        caption: "전표일자",
        width: 120,
      },
      {
        id: "col_ackey",
        field: "ackey",
        caption: "전표번호",
        width: 150,
      },
      {
        id: "col_cramt",
        field: "cramt",
        caption: "차변금액",
        width: 100,
      },
      {
        id: "col_dramt",
        field: "dramt",
        caption: "대변금액",
        width: 100,
      },
      {
        id: "col_remark3",
        field: "remark3",
        caption: "적요",
        width: 200,
      },
    ],
  },
];
