import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_MAESU",
        field: "MAESU",
        caption: "매수",
        width: 120,
      },
      {
        id: "col_location",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_custregnum",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_AMT",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "부가세액",
        width: 100,
      },
      {
        id: "col_compclass",
        field: "compclass",
        caption: "업태",
        width: 120,
      },
      {
        id: "col_comptype",
        field: "comptype",
        caption: "업종",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_MAESU2",
        field: "MAESU",
        caption: "매수",
        width: 120,
      },
      {
        id: "col_location2",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_custregnum2",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_custnm2",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_AMT2",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt2",
        field: "taxamt",
        caption: "부가세액",
        width: 100,
      },
      {
        id: "col_compclass2",
        field: "compclass",
        caption: "업태",
        width: 120,
      },
      {
        id: "col_comptype2",
        field: "comptype",
        caption: "업종",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_MAESU3",
        field: "MAESU",
        caption: "매수",
        width: 120,
      },
      {
        id: "col_location3",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_custregnum3",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_custnm3",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_AMT3",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt3",
        field: "taxamt",
        caption: "부가세액",
        width: 100,
      },
      {
        id: "col_compclass3",
        field: "compclass",
        caption: "업태",
        width: 120,
      },
      {
        id: "col_comptype3",
        field: "comptype",
        caption: "업종",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_MAESU4",
        field: "MAESU",
        caption: "매수",
        width: 120,
      },
      {
        id: "col_location4",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_AMT4",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt4",
        field: "taxamt",
        caption: "부가세액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList5",
    columns: [
      {
        id: "col_location5",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_gubunnm5",
        field: "gubunnm",
        caption: "카드구분",
        width: 120,
      },
      {
        id: "col_MAESU5",
        field: "MAESU",
        caption: "매수",
        width: 120,
      },
      {
        id: "col_AMT5",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt5",
        field: "taxamt",
        caption: "부가세액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList6",
    columns: [
      {
        id: "col_location6",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_splyAMT6",
        field: "splyAMT",
        caption: "공급가액",
        width: 100,
      },
      {
        id: "col_taxamt6",
        field: "taxamt",
        caption: "부가세액",
        width: 100,
      },
      {
        id: "col_custnm6",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_custregnum6",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_creditnum6",
        field: "creditnum",
        caption: "신용카드번호",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList7",
    columns: [
      {
        id: "col_location7",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_CUST_17",
        field: "CUST_1",
        caption: "거래처[전체]",
        width: 120,
      },
      {
        id: "col_MAESU17",
        field: "MAESU1",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_AMT17",
        field: "AMT1",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CUST_27",
        field: "CUST_2",
        caption: "거래처[법인]",
        width: 120,
      },
      {
        id: "col_MAESU27",
        field: "MAESU2",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_AMT27",
        field: "AMT2",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CUST_37",
        field: "CUST_3",
        caption: "거래처[개인]",
        width: 120,
      },
      {
        id: "col_MAESU37",
        field: "MAESU3",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_AMT37",
        field: "AMT3",
        caption: "금액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList8",
    columns: [
      {
        id: "col_location8",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_CUST_18",
        field: "CUST_1",
        caption: "거래처[전체]",
        width: 120,
      },
      {
        id: "col_MAESU18",
        field: "MAESU1",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_AMT18",
        field: "AMT1",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CUST_28",
        field: "CUST_2",
        caption: "거래처[법인]",
        width: 120,
      },
      {
        id: "col_MAESU28",
        field: "MAESU2",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_AMT28",
        field: "AMT2",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CUST_38",
        field: "CUST_3",
        caption: "거래처[개인]",
        width: 120,
      },
      {
        id: "col_MAESU38",
        field: "MAESU3",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_AMT38",
        field: "AMT3",
        caption: "금액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList9",
    columns: [
      {
        id: "col_location9",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_bizdiv9",
        field: "bizdiv",
        caption: "사업자구분",
        width: 120,
      },
      {
        id: "col_AMT9",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_custcd9",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm9",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_custregnum9",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_CONT9",
        field: "CONT",
        caption: "매수",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList10",
    columns: [
      {
        id: "col_location10",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_CUST_C10",
        field: "CUST_C",
        caption: "거래처갯수",
        width: 100,
      },
      {
        id: "col_MAESU_C10",
        field: "MAESU_C",
        caption: "계산서매수",
        width: 100,
      },
      {
        id: "col_AMT_C10",
        field: "AMT_C",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CHK_C10",
        field: "CHK_C",
        caption: "체크",
        width: 50,
      },
    ],
  },
  {
    gridName: "grdList11",
    columns: [
      {
        id: "col_location11",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_CUST_C11",
        field: "CUST_C",
        caption: "거래처갯수",
        width: 100,
      },
      {
        id: "col_MAESU_C11",
        field: "MAESU_C",
        caption: "계산서매수",
        width: 100,
      },
      {
        id: "col_AMT_C11",
        field: "AMT_C",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CHK_C11",
        field: "CHK_C",
        caption: "체크",
        width: 50,
      },
    ],
  },
  {
    gridName: "grdList12",
    columns: [
      {
        id: "col_location12",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_AMT12",
        field: "AMT",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_CONT12",
        field: "CONT",
        caption: "매수",
        width: 100,
      },
      {
        id: "col_custregnum12",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_custnm12",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList13",
    columns: [
      {
        id: "col_location13",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_mngdatanm113",
        field: "mngdatanm1",
        caption: "수출신고번호",
        width: 150,
      },
      {
        id: "col_shipdt13",
        field: "shipdt",
        caption: "선적일자",
        width: 120,
      },
      {
        id: "col_mngdata313",
        field: "mngdata3",
        caption: "통화",
        width: 150,
      },
      {
        id: "col_rate13",
        field: "rate",
        caption: "환율",
        width: 100,
      },
      {
        id: "col_mngamt13",
        field: "mngamt",
        caption: "외화금액",
        width: 100,
      },
      {
        id: "col_slipamt13",
        field: "slipamt",
        caption: "원화금액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList14",
    columns: [
      {
        id: "col_location14",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_mngdatanm114",
        field: "mngdatanm1",
        caption: "수출신고번호",
        width: 150,
      },
      {
        id: "col_shipdt14",
        field: "shipdt",
        caption: "선적일자",
        width: 120,
      },
      {
        id: "col_mngdata314",
        field: "mngdata3",
        caption: "통화",
        width: 150,
      },
      {
        id: "col_rate14",
        field: "rate",
        caption: "환율",
        width: 100,
      },
      {
        id: "col_mngamt14",
        field: "mngamt",
        caption: "외화금액",
        width: 100,
      },
      {
        id: "col_slipamt14",
        field: "slipamt",
        caption: "원화금액",
        width: 100,
      },
    ],
  },
];
