import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_num",
        field: "num",
        caption: "NO",
        width: 60,
      },
      {
        id: "col_custdiv",
        field: "custdiv",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 200,
      },
      {
        id: "col_itemlvl3",
        field: "itemlvl3",
        caption: "개발분야",
        width: 120,
      },
      {
        id: "col_meet_cnt",
        field: "meet_cnt",
        caption: "상담 수",
        width: 100,
      },
      {
        id: "col_esti_cnt",
        field: "esti_cnt",
        caption: "견적 수",
        width: 100,
      },
      {
        id: "col_cont_cnt",
        field: "cont_cnt",
        caption: "계약 수",
        width: 100,
      },
      {
        id: "col_cont_amt",
        field: "cont_amt",
        caption: "계약금액",
        width: 100,
      },
      {
        id: "col_amt",
        field: "amt",
        caption: "기청구액",
        width: 100,
      },
      {
        id: "col_no_amt",
        field: "no_amt",
        caption: "미청구액",
        width: 100,
      },
      {
        id: "col_misu_amt",
        field: "misu_amt",
        caption: "미수금액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_ref_key",
        field: "ref_key",
        caption: "PJT NO.",
        width: 150,
      },
      {
        id: "col_recdt",
        field: "recdt",
        caption: "작성일자",
        width: 120,
      },
      {
        id: "col_person",
        field: "person",
        caption: "작성자",
        width: 120,
      },
      {
        id: "col_usegb",
        field: "usegb",
        caption: "목적",
        width: 120,
      },
      {
        id: "col_type",
        field: "type",
        caption: "유형",
        width: 120,
      },
      {
        id: "col_custprsnnm",
        field: "custprsnnm",
        caption: "의뢰자명",
        width: 120,
      },
      {
        id: "col_materialtype",
        field: "materialtype",
        caption: "물질분야",
        width: 120,
      },
      {
        id: "col_extra_field2",
        field: "extra_field2",
        caption: "물질상세분야",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_quonum_quo",
        field: "quonum",
        caption: "PJT NO.",
        width: 150,
      },
      {
        id: "col_quorev_quo",
        field: "quorev",
        caption: "REV",
        width: 60,
      },
      {
        id: "col_custnm_quo",
        field: "custnm",
        caption: "업체명",
        width: 200,
      },
      {
        id: "col_custprsnnm_quo",
        field: "custprsnnm",
        caption: "의뢰자",
        width: 120,
      },
      {
        id: "col_materialtype_quo",
        field: "materialtype",
        caption: "물질분야",
        width: 120,
      },
      {
        id: "col_extra_field2_quo",
        field: "extra_field2",
        caption: "물질상세분야",
        width: 120,
      },
      {
        id: "col_itemcnt_quo",
        field: "itemcnt",
        caption: "의뢰품목수",
        width: 100,
      },
      {
        id: "col_designcnt_quo",
        field: "designcnt",
        caption: "디자인 입력수",
        width: 120,
      },
      {
        id: "col_quocalyn_quo",
        field: "quocalyn",
        caption: "견적산출여부",
        width: 120,
      },
      {
        id: "col_contractyn_quo",
        field: "contractyn",
        caption: "계약확정여부",
        width: 120,
      },
      {
        id: "col_quounp_quo",
        field: "quounp",
        caption: "견적원가",
        width: 100,
      },
      {
        id: "col_margin_quo",
        field: "margin",
        caption: "마진률",
        width: 100,
      },
      {
        id: "col_marginamt_quo",
        field: "marginamt",
        caption: "마진금액",
        width: 100,
      },
      {
        id: "col_discount_quo",
        field: "discount",
        caption: "할인률",
        width: 100,
      },
      {
        id: "col_discountamt_quo",
        field: "discountamt",
        caption: "할인금액",
        width: 100,
      },
      {
        id: "col_finalquowonamt_quo",
        field: "finalquowonamt",
        caption: "최종견적금액",
        width: 130,
      },
      {
        id: "col_person_quo",
        field: "person",
        caption: "영업담당자",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_quokey_list",
        field: "quokey",
        caption: "PJT NO.",
        width: 150,
      },
      {
        id: "col_ordnum_list",
        field: "ordnum",
        caption: "수주번호",
        width: 150,
      },
      {
        id: "col_contractno_list",
        field: "contractno",
        caption: "계약번호",
        width: 120,
      },
      {
        id: "col_cotracdt_list",
        field: "cotracdt",
        caption: "계약일자",
        width: 120,
      },
      {
        id: "col_strdt_list",
        field: "strdt",
        caption: "계약시작일",
        width: 120,
      },
      {
        id: "col_enddt_list",
        field: "enddt",
        caption: "계약종료일",
        width: 120,
      },
      {
        id: "col_contracyn",
        field: "contracyn",
        caption: "계약완료여부",
        width: 120,
      },
      {
        id: "col_project_list",
        field: "project",
        caption: "계약명",
        width: 200,
      },
      {
        id: "col_custnm_list",
        field: "custnm",
        caption: "업체명",
        width: 250,
      },
      {
        id: "col_custprsnnm_list",
        field: "custprsnnm",
        caption: "의뢰자",
        width: 120,
      },
      {
        id: "col_chkperson_list",
        field: "chkperson",
        caption: "영업담당자",
        width: 120,
      },
      {
        id: "col_materialtype_list",
        field: "materialtype",
        caption: "물질분야",
        width: 120,
      },
      {
        id: "col_extra_field2_list",
        field: "extra_field2",
        caption: "물질상세분야",
        width: 120,
      },
      {
        id: "col_materialnm_list",
        field: "materialnm",
        caption: "시험물질명",
        width: 150,
      },
      {
        id: "col_cnt1_list",
        field: "cnt1",
        caption: "계약품목수",
        width: 100,
      },
      {
        id: "col_amt_list",
        field: "amt",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt_list",
        field: "taxamt",
        caption: "세액",
        width: 100,
      },
      {
        id: "col_contraamt_list",
        field: "contraamt",
        caption: "계약금액",
        width: 100,
      },
      {
        id: "col_change_contraamt_list",
        field: "change_contraamt",
        caption: "변경계약금액",
        width: 130,
      },
      {
        id: "col_fin_contraamt_list",
        field: "fin_contraamt",
        caption: "최종계약금액",
        width: 130,
      },
    ],
  },
];
