import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_dptcd",
        field: "dptcd",
        caption: "부서코드",
        width: 150,
      },
      {
        id: "col_dptnm",
        field: "dptnm",
        caption: "부서명",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_pgmdiv",
        field: "pgmdiv",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_dptcd2",
        field: "dptcd",
        caption: "부서",
        width: 120,
      },
      {
        id: "col_postcd",
        field: "postcd",
        caption: "직위",
        width: 120,
      },
      {
        id: "col_user_id",
        field: "user_id",
        caption: "사원",
        width: 120,
      },
      {
        id: "col_devdiv",
        field: "devdiv",
        caption: "실적개발구분",
        width: 120,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_totdircost",
        field: "totdircost",
        caption: "합계",
        width: 100,
      },
      {
        id: "col_dircost01",
        field: "dircost01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_dircost02",
        field: "dircost02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_dircost03",
        field: "dircost03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_dircost04",
        field: "dircost04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_dircost05",
        field: "dircost05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_dircost06",
        field: "dircost06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_dircost07",
        field: "dircost07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_dircost08",
        field: "dircost08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_dircost09",
        field: "dircost09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_dircost10",
        field: "dircost10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_dircost11",
        field: "dircost11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_dircost12",
        field: "dircost12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 200,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_title",
        field: "title",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_amt01",
        field: "amt01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_amt02",
        field: "amt02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_amt03",
        field: "amt03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_amt04",
        field: "amt04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_amt05",
        field: "amt05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_amt06",
        field: "amt06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_amt07",
        field: "amt07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_amt08",
        field: "amt08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_amt09",
        field: "amt09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_amt10",
        field: "amt10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_amt11",
        field: "amt11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_amt12",
        field: "amt12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "합계",
        width: 100,
      },
    ],
  },
];
