import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_dptcd",
        field: "dptcd",
        caption: "부서코드",
        width: 150,
      },
      {
        id: "col_dptnm",
        field: "dptnm",
        caption: "부서명",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_pgmdiv",
        field: "pgmdiv",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_dptcd2",
        field: "dptcd",
        caption: "부서",
        width: 120,
      },
      {
        id: "col_postcd",
        field: "postcd",
        caption: "직위",
        width: 120,
      },
      {
        id: "col_user_id",
        field: "user_id",
        caption: "사원",
        width: 120,
      },
      {
        id: "col_devdiv",
        field: "devdiv",
        caption: "실적개발구분",
        width: 120,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_totdircost",
        field: "totdircost",
        caption: "합계",
        width: 100,
      },
      {
        id: "col_dircost01",
        field: "dircost01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_dircost02",
        field: "dircost02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_dircost03",
        field: "dircost03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_dircost04",
        field: "dircost04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_dircost05",
        field: "dircost05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_dircost06",
        field: "dircost06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_dircost07",
        field: "dircost07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_dircost08",
        field: "dircost08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_dircost09",
        field: "dircost09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_dircost10",
        field: "dircost10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_dircost11",
        field: "dircost11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_dircost12",
        field: "dircost12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 200,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_title",
        field: "title",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_amt01",
        field: "amt01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_amt02",
        field: "amt02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_amt03",
        field: "amt03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_amt04",
        field: "amt04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_amt05",
        field: "amt05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_amt06",
        field: "amt06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_amt07",
        field: "amt07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_amt08",
        field: "amt08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_amt09",
        field: "amt09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_amt10",
        field: "amt10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_amt11",
        field: "amt11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_amt12",
        field: "amt12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "합계",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_dptcd4",
        field: "dptcd",
        caption: "부서",
        width: 120,
      },
      {
        id: "col_user_id4",
        field: "user_id",
        caption: "사원",
        width: 120,
      },
      {
        id: "col_dircost4",
        field: "dircost",
        caption: "직접비",
        width: 100,
      },
      {
        id: "col_indircost4",
        field: "indircost",
        caption: "간접비",
        width: 100,
      },
      {
        id: "col_royalty4",
        field: "royalty",
        caption: "기술료",
        width: 100,
      },
      {
        id: "col_totcost4",
        field: "totcost",
        caption: "목표금액",
        width: 100,
      },
      {
        id: "col_dircost014",
        field: "dircost01",
        caption: "1월 직접비",
        width: 100,
      },
      {
        id: "col_dircost024",
        field: "dircost02",
        caption: "2월 직접비",
        width: 100,
      },
      {
        id: "col_dircost034",
        field: "dircost03",
        caption: "3월 직접비",
        width: 100,
      },
      {
        id: "col_dircost044",
        field: "dircost04",
        caption: "4월 직접비",
        width: 100,
      },
      {
        id: "col_dircost054",
        field: "dircost05",
        caption: "5월 직접비",
        width: 100,
      },
      {
        id: "col_dircost064",
        field: "dircost06",
        caption: "6월 직접비",
        width: 100,
      },
      {
        id: "col_dircost074",
        field: "dircost07",
        caption: "7월 직접비",
        width: 100,
      },
      {
        id: "col_dircost084",
        field: "dircost08",
        caption: "8월 직접비",
        width: 100,
      },
      {
        id: "col_dircost094",
        field: "dircost09",
        caption: "9월 직접비",
        width: 100,
      },
      {
        id: "col_dircost104",
        field: "dircost10",
        caption: "10월 직접비",
        width: 100,
      },
      {
        id: "col_dircost114",
        field: "dircost11",
        caption: "11월 직접비",
        width: 100,
      },
      {
        id: "col_dircost124",
        field: "dircost12",
        caption: "12월 직접비",
        width: 100,
      },
      {
        id: "col_indircost014",
        field: "indircost01",
        caption: "1월 간접비",
        width: 100,
      },
      {
        id: "col_indircost024",
        field: "indircost02",
        caption: "2월 간접비",
        width: 100,
      },
      {
        id: "col_indircost034",
        field: "indircost03",
        caption: "3월 간접비",
        width: 100,
      },
      {
        id: "col_indircost044",
        field: "indircost04",
        caption: "4월 간접비",
        width: 100,
      },
      {
        id: "col_indircost054",
        field: "indircost05",
        caption: "5월 간접비",
        width: 100,
      },
      {
        id: "col_indircost064",
        field: "indircost06",
        caption: "6월 간접비",
        width: 100,
      },
      {
        id: "col_indircost074",
        field: "indircost07",
        caption: "7월 간접비",
        width: 100,
      },
      {
        id: "col_indircost084",
        field: "indircost08",
        caption: "8월 간접비",
        width: 100,
      },
      {
        id: "col_indircost094",
        field: "indircost09",
        caption: "9월 간접비",
        width: 100,
      },
      {
        id: "col_indircost104",
        field: "indircost10",
        caption: "10월 간접비",
        width: 100,
      },
      {
        id: "col_indircost114",
        field: "indircost11",
        caption: "11월 간접비",
        width: 100,
      },
      {
        id: "col_indircost124",
        field: "indircost12",
        caption: "12월 간접비",
        width: 100,
      },
      {
        id: "col_royalty014",
        field: "royalty01",
        caption: "1월 기술료",
        width: 100,
      },
      {
        id: "col_royalty024",
        field: "royalty02",
        caption: "2월 기술료",
        width: 100,
      },
      {
        id: "col_royalty034",
        field: "royalty03",
        caption: "3월 기술료",
        width: 100,
      },
      {
        id: "col_royalty044",
        field: "royalty04",
        caption: "4월 기술료",
        width: 100,
      },
      {
        id: "col_royalty054",
        field: "royalty05",
        caption: "5월 기술료",
        width: 100,
      },
      {
        id: "col_royalty064",
        field: "royalty06",
        caption: "6월 기술료",
        width: 100,
      },
      {
        id: "col_royalty074",
        field: "royalty07",
        caption: "7월 기술료",
        width: 100,
      },
      {
        id: "col_royalty084",
        field: "royalty08",
        caption: "8월 기술료",
        width: 100,
      },
      {
        id: "col_royalty094",
        field: "royalty09",
        caption: "9월 기술료",
        width: 100,
      },
      {
        id: "col_royalty104",
        field: "royalty10",
        caption: "10월 기술료",
        width: 100,
      },
      {
        id: "col_royalty114",
        field: "royalty11",
        caption: "11월 기술료",
        width: 100,
      },
      {
        id: "col_royalty124",
        field: "royalty12",
        caption: "12월 기술료",
        width: 100,
      },
      {
        id: "col_totcost014",
        field: "totcost01",
        caption: "1월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost024",
        field: "totcost02",
        caption: "2월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost034",
        field: "totcost03",
        caption: "3월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost044",
        field: "totcost04",
        caption: "4월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost054",
        field: "totcost05",
        caption: "5월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost064",
        field: "totcost06",
        caption: "6월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost074",
        field: "totcost07",
        caption: "7월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost084",
        field: "totcost08",
        caption: "8월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost094",
        field: "totcost09",
        caption: "9월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost104",
        field: "totcost10",
        caption: "10월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost114",
        field: "totcost11",
        caption: "11월 목표금액",
        width: 100,
      },
      {
        id: "col_totcost124",
        field: "totcost12",
        caption: "12월 목표금액",
        width: 100,
      },
      {
        id: "col_remark4",
        field: "remark",
        caption: "비고",
        width: 200,
      },
    ],
  },
];
