import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_dt_01",
        field: "dt_01",
        caption: "1일",
        width: 100,
      },
      {
        id: "col_dt_02",
        field: "dt_02",
        caption: "2일",
        width: 100,
      },
      {
        id: "col_dt_03",
        field: "dt_03",
        caption: "3일",
        width: 100,
      },
      {
        id: "col_dt_04",
        field: "dt_04",
        caption: "4일",
        width: 100,
      },
      {
        id: "col_dt_05",
        field: "dt_05",
        caption: "5일",
        width: 100,
      },
      {
        id: "col_dt_06",
        field: "dt_06",
        caption: "6일",
        width: 100,
      },
      {
        id: "col_dt_07",
        field: "dt_07",
        caption: "7일",
        width: 100,
      },
      {
        id: "col_dt_08",
        field: "dt_08",
        caption: "8일",
        width: 100,
      },
      {
        id: "col_dt_09",
        field: "dt_09",
        caption: "9일",
        width: 100,
      },
      {
        id: "col_dt_10",
        field: "dt_10",
        caption: "10일",
        width: 100,
      },
      {
        id: "col_dt_11",
        field: "dt_11",
        caption: "11일",
        width: 100,
      },
      {
        id: "col_dt_12",
        field: "dt_12",
        caption: "12일",
        width: 100,
      },
      {
        id: "col_dt_13",
        field: "dt_13",
        caption: "13일",
        width: 100,
      },
      {
        id: "col_dt_14",
        field: "dt_14",
        caption: "14일",
        width: 100,
      },
      {
        id: "col_dt_15",
        field: "dt_15",
        caption: "15일",
        width: 100,
      },
      {
        id: "col_dt_16",
        field: "dt_16",
        caption: "16일",
        width: 100,
      },
      {
        id: "col_dt_17",
        field: "dt_17",
        caption: "17일",
        width: 100,
      },
      {
        id: "col_dt_18",
        field: "dt_18",
        caption: "18일",
        width: 100,
      },
      {
        id: "col_dt_19",
        field: "dt_19",
        caption: "19일",
        width: 100,
      },
      {
        id: "col_dt_20",
        field: "dt_20",
        caption: "20일",
        width: 100,
      },
      {
        id: "col_dt_21",
        field: "dt_21",
        caption: "21일",
        width: 100,
      },
      {
        id: "col_dt_22",
        field: "dt_22",
        caption: "22일",
        width: 100,
      },
      {
        id: "col_dt_23",
        field: "dt_23",
        caption: "23일",
        width: 100,
      },
      {
        id: "col_dt_24",
        field: "dt_24",
        caption: "24일",
        width: 100,
      },
      {
        id: "col_dt_25",
        field: "dt_25",
        caption: "25일",
        width: 100,
      },
      {
        id: "col_dt_26",
        field: "dt_26",
        caption: "26일",
        width: 100,
      },
      {
        id: "col_dt_27",
        field: "dt_27",
        caption: "27일",
        width: 100,
      },
      {
        id: "col_dt_28",
        field: "dt_28",
        caption: "28일",
        width: 100,
      },
      {
        id: "col_dt_29",
        field: "dt_29",
        caption: "29일",
        width: 100,
      },
      {
        id: "col_dt_30",
        field: "dt_30",
        caption: "30일",
        width: 100,
      },
      {
        id: "col_dt_31",
        field: "dt_31",
        caption: "31일",
        width: 100,
      },
      {
        id: "col_total",
        field: "total",
        caption: "총계",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_custcd2",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm2",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_dt_011",
        field: "dt_01",
        caption: "1월",
        width: 100,
      },
      {
        id: "col_dt_021",
        field: "dt_02",
        caption: "2월",
        width: 100,
      },
      {
        id: "col_dt_031",
        field: "dt_03",
        caption: "3월",
        width: 100,
      },
      {
        id: "col_dt_041",
        field: "dt_04",
        caption: "4월",
        width: 100,
      },
      {
        id: "col_dt_051",
        field: "dt_05",
        caption: "5월",
        width: 100,
      },
      {
        id: "col_dt_061",
        field: "dt_06",
        caption: "6월",
        width: 100,
      },
      {
        id: "col_dt_071",
        field: "dt_07",
        caption: "7월",
        width: 100,
      },
      {
        id: "col_dt_081",
        field: "dt_08",
        caption: "8월",
        width: 100,
      },
      {
        id: "col_dt_091",
        field: "dt_09",
        caption: "9월",
        width: 100,
      },
      {
        id: "col_dt_101",
        field: "dt_10",
        caption: "10월",
        width: 100,
      },
      {
        id: "col_dt_111",
        field: "dt_11",
        caption: "11월",
        width: 100,
      },
      {
        id: "col_dt_121",
        field: "dt_12",
        caption: "12월",
        width: 100,
      },
      {
        id: "col_total2",
        field: "total",
        caption: "총계",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_strtime",
        field: "strtime",
        caption: "작성일자",
        width: 120,
      },
      {
        id: "col_user_name",
        field: "user_name",
        caption: "사용자명",
        width: 120,
      },
      {
        id: "col_title",
        field: "title",
        caption: "제목",
        width: 120,
      },
      {
        id: "col_contents",
        field: "contents",
        caption: "내용",
        width: 200,
      },
      {
        id: "col_usetime",
        field: "usetime",
        caption: "소요시간",
        width: 120,
      },
    ],
  },
];
