import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_prsnnum",
        field: "prsnnum",
        caption: "사번",
        width: 150,
      },
      {
        id: "col_prsnnm",
        field: "prsnnm",
        caption: "성명",
        width: 150,
      },
      {
        id: "col_dptnm",
        field: "dptnm",
        caption: "부서",
        width: 120,
      },
      {
        id: "col_postcd",
        field: "postcd",
        caption: "직위",
        width: 120,
      },
      {
        id: "col_perregnum",
        field: "perregnum",
        caption: "주민번호",
        width: 120,
      },
      {
        id: "col_regorgdt",
        field: "regorgdt",
        caption: "입사일",
        width: 120,
      },
      {
        id: "col_anlslry",
        field: "anlslry",
        caption: "연봉",
        width: 100,
      },
      {
        id: "col_wmn",
        field: "wmn",
        caption: "부녀자",
        width: 80,
      },
      {
        id: "col_spf",
        field: "spf",
        caption: "한부모공제여부",
        width: 80,
      },
      {
        id: "col_orgdiv",
        field: "orgdiv",
        caption: "회사구분",
        width: 120,
      },
      {
        id: "col_workplace",
        field: "workplace",
        caption: "근무지",
        width: 120,
      },
      {
        id: "col_location",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_position",
        field: "position",
        caption: "사업부",
        width: 120,
      },
      {
        id: "col_prsnnmh",
        field: "prsnnmh",
        caption: "성명(한문)",
        width: 120,
      },
      {
        id: "col_prsnnme",
        field: "prsnnme",
        caption: "성명(영문)",
        width: 120,
      },
      {
        id: "col_nationcd",
        field: "nationcd",
        caption: "국적",
        width: 120,
      },
      {
        id: "col_cardcd",
        field: "cardcd",
        caption: "카드번호",
        width: 120,
      },
      {
        id: "col_dptcd",
        field: "dptcd",
        caption: "부서코드",
        width: 120,
      },
      {
        id: "col_ocptcd",
        field: "ocptcd",
        caption: "작업조",
        width: 120,
      },
      {
        id: "col_workgb",
        field: "workgb",
        caption: "근무형태",
        width: 120,
      },
      {
        id: "col_workcls",
        field: "workcls",
        caption: "근무조",
        width: 120,
      },
      {
        id: "col_jobcd",
        field: "jobcd",
        caption: "직무코드",
        width: 120,
      },
      {
        id: "col_abilcd",
        field: "abilcd",
        caption: "직책",
        width: 120,
      },
      {
        id: "col_paygrad",
        field: "paygrad",
        caption: "직급",
        width: 120,
      },
      {
        id: "col_salaryclass",
        field: "salaryclass",
        caption: "호봉",
        width: 120,
      },
      {
        id: "col_regcd",
        field: "regcd",
        caption: "입사구분",
        width: 120,
      },
      {
        id: "col_birdt",
        field: "birdt",
        caption: "생년월일",
        width: 120,
      },
      {
        id: "col_bircd",
        field: "bircd",
        caption: "음양",
        width: 150,
      },
      {
        id: "col_sexcd",
        field: "sexcd",
        caption: "성별",
        width: 150,
      },
      {
        id: "col_imdate",
        field: "imdate",
        caption: "근속기준일",
        width: 120,
      },
      {
        id: "col_firredt",
        field: "firredt",
        caption: "정산입사일",
        width: 120,
      },
      {
        id: "col_rtrdt",
        field: "rtrdt",
        caption: "퇴사일",
        width: 120,
      },
      {
        id: "col_rtrrsn",
        field: "rtrrsn",
        caption: "퇴직사유",
        width: 120,
      },
      {
        id: "col_emptype",
        field: "emptype",
        caption: "사원구분",
        width: 120,
      },
      {
        id: "col_zipcode",
        field: "zipcode",
        caption: "우편번호",
        width: 120,
      },
      {
        id: "col_koraddr",
        field: "koraddr",
        caption: "주민등록지주소",
        width: 120,
      },
      {
        id: "col_hmzipcode",
        field: "hmzipcode",
        caption: "주민등록지우편번호",
        width: 120,
      },
      {
        id: "col_hmaddr",
        field: "hmaddr",
        caption: "실제거주지주소",
        width: 120,
      },
      {
        id: "col_phonenum",
        field: "phonenum",
        caption: "전화번호",
        width: 120,
      },
      {
        id: "col_extnum",
        field: "extnum",
        caption: "내선번호",
        width: 120,
      },
      {
        id: "col_outnum",
        field: "outnum",
        caption: "외선번호",
        width: 120,
      },
      {
        id: "col_schcd",
        field: "schcd",
        caption: "최종학력",
        width: 120,
      },
      {
        id: "col_gradutype",
        field: "gradutype",
        caption: "졸업구분",
        width: 120,
      },
      {
        id: "col_directyn",
        field: "directyn",
        caption: "직간접구분",
        width: 80,
      },
      {
        id: "col_laboryn",
        field: "laboryn",
        caption: "노조가입",
        width: 80,
      },
      {
        id: "col_dfmyn",
        field: "dfmyn",
        caption: "신체장애",
        width: 80,
      },
      {
        id: "col_milyn",
        field: "milyn",
        caption: "병역특례",
        width: 80,
      },
      {
        id: "col_paycd",
        field: "paycd",
        caption: "급여지급유형",
        width: 120,
      },
      {
        id: "col_taxcd",
        field: "taxcd",
        caption: "세액구분",
        width: 120,
      },
      {
        id: "col_hirinsuyn",
        field: "hirinsuyn",
        caption: "고용보험여부",
        width: 80,
      },
      {
        id: "col_payyn",
        field: "payyn",
        caption: "급여지급구분",
        width: 120,
      },
      {
        id: "col_rtrgivdiv",
        field: "rtrgivdiv",
        caption: "퇴직금지급구분",
        width: 120,
      },
      {
        id: "col_yrgivdiv",
        field: "yrgivdiv",
        caption: "년차수당지급구분",
        width: 120,
      },
      {
        id: "col_mongivdiv",
        field: "mongivdiv",
        caption: "월차지급방법",
        width: 120,
      },
      {
        id: "col_caltaxyn",
        field: "caltaxyn",
        caption: "세액계산대상여부",
        width: 80,
      },
      {
        id: "col_yrdclyn",
        field: "yrdclyn",
        caption: "연말정산신고대상여부",
        width: 80,
      },
      {
        id: "col_bankcd",
        field: "bankcd",
        caption: "은행코드",
        width: 120,
      },
      {
        id: "col_bankacnt",
        field: "bankacnt",
        caption: "계좌번호",
        width: 120,
      },
      {
        id: "col_backacntuser",
        field: "backacntuser",
        caption: "예금주",
        width: 120,
      },
      {
        id: "col_insuzon",
        field: "insuzon",
        caption: "보험지역",
        width: 120,
      },
      {
        id: "col_medgrad",
        field: "medgrad",
        caption: "의료보험등급",
        width: 120,
      },
      {
        id: "col_medinsunumr",
        field: "medinsunum",
        caption: "의료보험번호",
        width: 120,
      },
      {
        id: "col_pnsgrad",
        field: "pnsgrad",
        caption: "국민연금등급",
        width: 120,
      },
      {
        id: "col_meddate",
        field: "meddate",
        caption: "건강보험취득일",
        width: 120,
      },
      {
        id: "col_anudate",
        field: "anudate",
        caption: "국민연금취득일",
        width: 120,
      },
      {
        id: "col_hirdate",
        field: "hirdate",
        caption: "고용보험취득일",
        width: 120,
      },
      {
        id: "col_sps",
        field: "sps",
        caption: "배우자유무",
        width: 80,
      },
      {
        id: "col_sptnum",
        field: "sptnum",
        caption: "부양자",
        width: 100,
      },
      {
        id: "col_dfmnum",
        field: "dfmnum",
        caption: "장애자",
        width: 100,
      },
      {
        id: "col_agenum",
        field: "agenum",
        caption: "경로자",
        width: 100,
      },
      {
        id: "col_brngchlnum",
        field: "brngchlnum",
        caption: "자녀양육",
        width: 100,
      },
      {
        id: "col_fam1",
        field: "fam1",
        caption: "가족수당배우",
        width: 100,
      },
      {
        id: "col_fam2",
        field: "fam2",
        caption: "가족수당자녀",
        width: 100,
      },
      {
        id: "col_monpay",
        field: "monpay",
        caption: "급여기준금",
        width: 100,
      },
      {
        id: "col_bnsstd",
        field: "bnsstd",
        caption: "상여기준금",
        width: 100,
      },
      {
        id: "col_rate",
        field: "rate",
        caption: "상여지급률",
        width: 120,
      },
      {
        id: "col_daypay",
        field: "daypay",
        caption: "일급",
        width: 100,
      },
      {
        id: "col_dailypay",
        field: "dailypay",
        caption: "일당",
        width: 100,
      },
      {
        id: "col_timepay",
        field: "timepay",
        caption: "시급",
        width: 100,
      },
      {
        id: "col_overtimepay",
        field: "overtimepay",
        caption: "고정연장수당",
        width: 100,
      },
      {
        id: "col_toutpay",
        field: "toutpay",
        caption: "시간외수당",
        width: 100,
      },
      {
        id: "col_notaxe",
        field: "notaxe",
        caption: "국외근로대상",
        width: 80,
      },
      {
        id: "col_otkind",
        field: "otkind",
        caption: "잔업수당계산구분자",
        width: 120,
      },
      {
        id: "col_bnskind",
        field: "bnskind",
        caption: "상여금계산구분자",
        width: 80,
      },
      {
        id: "col_payprovyn",
        field: "payprovyn",
        caption: "지급여부",
        width: 120,
      },
      {
        id: "col_mailid",
        field: "mailid",
        caption: "개인메일",
        width: 120,
      },
      {
        id: "col_workmail",
        field: "workmail",
        caption: "메일주소(회사)",
        width: 120,
      },
      {
        id: "col_childnum",
        field: "childnum",
        caption: "다자녀",
        width: 100,
      },
      {
        id: "col_dfmyn2",
        field: "dfmyn2",
        caption: "경감보험대상",
        width: 80,
      },
      {
        id: "col_houseyn",
        field: "houseyn",
        caption: "세대주여부",
        width: 200,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 120,
      },
      {
        id: "col_height",
        field: "height",
        caption: "신장",
        width: 100,
      },
      {
        id: "col_weight",
        field: "weight",
        caption: "체중",
        width: 100,
      },
      {
        id: "col_blood",
        field: "blood",
        caption: "혈액형",
        width: 120,
      },
      {
        id: "col_color",
        field: "color",
        caption: "색맹",
        width: 120,
      },
      {
        id: "col_leye",
        field: "leye",
        caption: "시력(좌)",
        width: 100,
      },
      {
        id: "col_reye",
        field: "reye",
        caption: "시력(우)",
        width: 100,
      },
      {
        id: "col_hobby",
        field: "hobby",
        caption: "취미",
        width: 120,
      },
      {
        id: "col_hobby2",
        field: "hobby2",
        caption: "특기",
        width: 120,
      },
      {
        id: "col_religion",
        field: "religion",
        caption: "종교",
        width: 120,
      },
      {
        id: "col_marriage",
        field: "marriage",
        caption: "결혼여부",
        width: 80,
      },
      {
        id: "col_marrydt",
        field: "marrydt",
        caption: "결혼기념일",
        width: 120,
      },
      {
        id: "col_orgaddr",
        field: "orgaddr",
        caption: "본적",
        width: 120,
      },
      {
        id: "col_birthplace",
        field: "birthplace",
        caption: "출생지",
        width: 120,
      },
      {
        id: "col_size1",
        field: "size1",
        caption: "의류(상)",
        width: 120,
      },
      {
        id: "col_size2",
        field: "size2",
        caption: "의류(하)",
        width: 120,
      },
      {
        id: "col_size3",
        field: "size3",
        caption: "신발",
        width: 120,
      },
      {
        id: "col_exmtaxgb",
        field: "exmtaxgb",
        caption: "취업청년세액감면",
        width: 120,
      },
      {
        id: "col_exstartdt",
        field: "exstartdt",
        caption: "감면시작",
        width: 120,
      },
      {
        id: "col_exenddt",
        field: "exenddt",
        caption: "감면종료",
        width: 120,
      },
    ],
  },
];
