import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_prsnnm",
        field: "prsnnm",
        caption: "성명",
        width: 150,
      },
      {
        id: "col_div",
        field: "div",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_duty1",
        field: "duty1",
        caption: "1일",
        width: 100,
      },
      {
        id: "col_duty2",
        field: "duty2",
        caption: "2일",
        width: 100,
      },
      {
        id: "col_duty3",
        field: "duty3",
        caption: "3일",
        width: 100,
      },
      {
        id: "col_duty4",
        field: "duty4",
        caption: "4일",
        width: 100,
      },
      {
        id: "col_duty5",
        field: "duty5",
        caption: "5일",
        width: 100,
      },
      {
        id: "col_duty6",
        field: "duty6",
        caption: "6일",
        width: 100,
      },
      {
        id: "col_duty7",
        field: "duty7",
        caption: "7일",
        width: 100,
      },
      {
        id: "col_duty8",
        field: "duty8",
        caption: "8일",
        width: 100,
      },
      {
        id: "col_duty9",
        field: "duty9",
        caption: "9일",
        width: 100,
      },
      {
        id: "col_duty10",
        field: "duty10",
        caption: "10일",
        width: 100,
      },
      {
        id: "col_duty11",
        field: "duty11",
        caption: "11일",
        width: 100,
      },
      {
        id: "col_duty12",
        field: "duty12",
        caption: "12일",
        width: 100,
      },
      {
        id: "col_duty13",
        field: "duty13",
        caption: "13일",
        width: 100,
      },
      {
        id: "col_duty14",
        field: "duty14",
        caption: "14일",
        width: 100,
      },
      {
        id: "col_duty15",
        field: "duty15",
        caption: "15일",
        width: 100,
      },
      {
        id: "col_duty16",
        field: "duty16",
        caption: "16일",
        width: 100,
      },

      {
        id: "col_duty17",
        field: "duty17",
        caption: "17일",
        width: 100,
      },
      {
        id: "col_duty18",
        field: "duty18",
        caption: "18일",
        width: 100,
      },
      {
        id: "col_duty19",
        field: "duty19",
        caption: "19일",
        width: 100,
      },
      {
        id: "col_duty20",
        field: "duty20",
        caption: "20일",
        width: 100,
      },
      {
        id: "col_duty21",
        field: "duty21",
        caption: "21일",
        width: 100,
      },
      {
        id: "col_duty22",
        field: "duty22",
        caption: "22일",
        width: 100,
      },
      {
        id: "col_duty23",
        field: "duty23",
        caption: "231일",
        width: 100,
      },
      {
        id: "col_duty24",
        field: "duty24",
        caption: "24일",
        width: 100,
      },
      {
        id: "col_duty25",
        field: "duty25",
        caption: "25일",
        width: 100,
      },
      {
        id: "col_duty26",
        field: "duty26",
        caption: "26일",
        width: 100,
      },
      {
        id: "col_duty27",
        field: "duty27",
        caption: "27일",
        width: 100,
      },
      {
        id: "col_duty28",
        field: "duty28",
        caption: "28일",
        width: 100,
      },
      {
        id: "col_duty29",
        field: "duty29",
        caption: "29일",
        width: 100,
      },
      {
        id: "col_duty30",
        field: "duty30",
        caption: "30일",
        width: 100,
      },
      {
        id: "col_duty31",
        field: "duty31",
        caption: "31일",
        width: 100,
      },
    ]
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_2prsnnm",
        field: "prsnnm",
        caption: "성명",
        width: 150,
      },
      {
        id: "col_2div",
        field: "div",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_2duty1",
        field: "duty1",
        caption: "1일",
        width: 100,
      },
      {
        id: "col_2duty2",
        field: "duty2",
        caption: "2일",
        width: 100,
      },
      {
        id: "col_2duty3",
        field: "duty3",
        caption: "3일",
        width: 100,
      },
      {
        id: "col_2duty4",
        field: "duty4",
        caption: "4일",
        width: 100,
      },
      {
        id: "col_2duty5",
        field: "duty5",
        caption: "5일",
        width: 100,
      },
      {
        id: "col_2duty6",
        field: "duty6",
        caption: "6일",
        width: 100,
      },
      {
        id: "col_2duty7",
        field: "duty7",
        caption: "7일",
        width: 100,
      },
      {
        id: "col_2duty8",
        field: "duty8",
        caption: "8일",
        width: 100,
      },
      {
        id: "col_2duty9",
        field: "duty9",
        caption: "9일",
        width: 100,
      },
      {
        id: "col_2duty10",
        field: "duty10",
        caption: "10일",
        width: 100,
      },
      {
        id: "col_2duty11",
        field: "duty11",
        caption: "11일",
        width: 100,
      },
      {
        id: "col_2duty12",
        field: "duty12",
        caption: "12일",
        width: 100,
      },
      {
        id: "col_2duty13",
        field: "duty13",
        caption: "13일",
        width: 100,
      },
      {
        id: "col_2duty14",
        field: "duty14",
        caption: "14일",
        width: 100,
      },
      {
        id: "col_2duty15",
        field: "duty15",
        caption: "15일",
        width: 100,
      },
      {
        id: "col_2duty16",
        field: "duty16",
        caption: "16일",
        width: 100,
      },

      {
        id: "col_2duty17",
        field: "duty17",
        caption: "17일",
        width: 100,
      },
      {
        id: "col_2duty18",
        field: "duty18",
        caption: "18일",
        width: 100,
      },
      {
        id: "col_2duty19",
        field: "duty19",
        caption: "19일",
        width: 100,
      },
      {
        id: "col_2duty20",
        field: "duty20",
        caption: "20일",
        width: 100,
      },
      {
        id: "col_2duty21",
        field: "duty21",
        caption: "21일",
        width: 100,
      },
      {
        id: "col_2duty22",
        field: "duty22",
        caption: "22일",
        width: 100,
      },
      {
        id: "col_2duty23",
        field: "duty23",
        caption: "231일",
        width: 100,
      },
      {
        id: "col_2duty24",
        field: "duty24",
        caption: "24일",
        width: 100,
      },
      {
        id: "col_2duty25",
        field: "duty25",
        caption: "25일",
        width: 100,
      },
      {
        id: "col_2duty26",
        field: "duty26",
        caption: "26일",
        width: 100,
      },
      {
        id: "col_2duty27",
        field: "duty27",
        caption: "27일",
        width: 100,
      },
      {
        id: "col_2duty28",
        field: "duty28",
        caption: "28일",
        width: 100,
      },
      {
        id: "col_2duty29",
        field: "duty29",
        caption: "29일",
        width: 100,
      },
      {
        id: "col_2duty30",
        field: "duty30",
        caption: "30일",
        width: 100,
      },
      {
        id: "col_2duty31",
        field: "duty31",
        caption: "31일",
        width: 100,
      },
    ]
  },
];
