import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_fxmngnum",
        field: "fxmngnum",
        caption: "장비관리번호",
        width: 150,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "품목규격",
        width: 120,
      },
      {
        id: "col_serialno",
        field: "serialno",
        caption: "시리얼No.",
        width: 120,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 120,
      },
      {
        id: "col_fxdiv",
        field: "fxdiv",
        caption: "장비구분",
        width: 120,
      },
      {
        id: "col_purdt",
        field: "purdt",
        caption: "구입일자",
        width: 120,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "구입처",
        width: 120,
      },
      {
        id: "col_outdt1",
        field: "outdt1",
        caption: "출하일자1",
        width: 120,
      },
      {
        id: "col_custcd1",
        field: "custcd1",
        caption: "출하처1",
        width: 120,
      },
      {
        id: "col_load_place1",
        field: "load_place1",
        caption: "적재장소1",
        width: 120,
      },
      {
        id: "col_outdt2",
        field: "outdt2",
        caption: "출하일자2",
        width: 120,
      },
      {
        id: "col_custcd2",
        field: "custcd2",
        caption: "출하처2",
        width: 120,
      },
      {
        id: "col_load_place2",
        field: "load_place2",
        caption: "적재장소2",
        width: 120,
      },
      {
        id: "col_outdt3",
        field: "outdt3",
        caption: "출하일자3",
        width: 120,
      },
      {
        id: "col_custcd3",
        field: "custcd3",
        caption: "출하처3",
        width: 120,
      },
      {
        id: "col_load_place3",
        field: "load_place3",
        caption: "적재장소3",
        width: 120,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 200,
      },
      {
        id: "col_asfin",
        field: "asfin",
        caption: "a/s 완료여부",
        width: 100,
      },
    ],
  },   {
    gridName: "grdList2",
    columns: [
      {
        id: "col_inexpdt",
        field: "inexpdt",
        caption: "입고예정일",
        width: 120,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계쩡",
        width: 120,
      },
      // {
      //   id: "col_insiz",
      //   field: "insiz",
      //   caption: "규격",
      //   width: 120,
      // },
      {
        id: "col_load_place",
        field: "load_place",
        caption: "창고",
        width: 120,
      },
      {
        id: "col_qty2",
        field: "qty",
        caption: "청구수량",
        width: 100,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "수량단위",
        width: 100,
      },
      {
        id: "col_unpcalmeth",
        field: "unpcalmeth",
        caption: "단가산정방법",
        width: 100,
      },
      {
        id: "col_unp",
        field: "unp",
        caption: "단가",
        width: 100,
      },
      {
        id: "col_amt2",
        field: "amt",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_wonamt",
        field: "wonamt",
        caption: "원화금액",
        width: 100,
      },
      {
        id: "col_taxamt2",
        field: "taxamt",
        caption: "세액",
        width: 100,
      },
      {
        id: "col_totamt2",
        field: "totamt",
        caption: "합계금액",
        width: 100,
      },
      // {
      //   id: "col_remark",
      //   field: "remark",
      //   caption: "비고",
      //   width: 200,
      // },
      {
        id: "col_reqkey2",
        field: "reqkey",
        caption: "청구번호",
        width: 150,
      },
      {
        id: "col_finyn",
        field: "finyn",
        caption: "완료여부",
        width: 100,
      },
    ],
  },
];
