import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_indt",
        field: "indt",
        caption: "입고일자",
        width: 100,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체코드",
        width: 100,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 170,
      },
      {
        id: "col_pac",
        field: "pac",
        caption: "도/사급",
        width: 100,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 200,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 170,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 170,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계정",
        width: 170,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 120,
      },
      {
        id: "col_doexdiv",
        field: "doexdiv",
        caption: "내수구분",
        width: 80,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 80,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "수량단위",
        width: 80,
      },
      {
        id: "col_amtunit",
        field: "amtunit",
        caption: "화폐단위",
        width: 100,
      },
      {
        id: "col_unp",
        field: "unp",
        caption: "단가",
        width: 80,
      },
      {
        id: "col_amt",
        field: "amt",
        caption: "공급가액",
        width: 80,
      },
      {
        id: "col_wonamt",
        field: "wonamt",
        caption: "원화금액",
        width: 80,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "세액",
        width: 80,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "합계금액",
        width: 100,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 150,
      },
      {
        id: "col_inkind",
        field: "inkind",
        caption: "입고유형",
        width: 100,
      },
      {
        id: "col_itemlvl1",
        field: "itemlvl1",
        caption: "대분류",
        width: 100,
      },
      {
        id: "col_itemlvl2",
        field: "itemlvl2",
        caption: "중분류",
        width: 100,
      },
      {
        id: "col_itemlvl3",
        field: "itemlvl3",
        caption: "소분류",
        width: 100,
      },
      {
        id: "col_files",
        field: "files",
        caption: "첨부파일",
        width: 80,
      },
      {
        id: "col_purdiv",
        field: "purdiv",
        caption: "발주형태",
        width: 100,
      },
      {
        id: "col_person",
        field: "person",
        caption: "담당자",
        width: 120,
      },
      {
        id: "col_saleItemcd",
        field: "saleItemcd",
        caption: "수주품목코드",
        width: 150,
      },
      {
        id: "col_saleItemnm",
        field: "saleItemnm",
        caption: "수주품목명",
        width: 120,
      },
    ],
  },
];
