import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdOrdList",
    columns: [
      {
        id: "col_orddt",
        field: "orddt",
        caption: "수주일자",
        width: 120,
      },
      {
        id: "col_dlvdt",
        field: "dlvdt",
        caption: "납기일자",
        width: 120,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체",
        width: 130,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 130,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 130,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계정",
        width: 130,
      },
      {
        id: "col_itemlvl1",
        field: "itemlvl1",
        caption: "대분류",
        width: 130,
      },
      {
        id: "col_itemlvl2",
        field: "itemlvl2",
        caption: "중분류",
        width: 130,
      },
      {
        id: "col_itemlvl3",
        field: "itemlvl3",
        caption: "소분류",
        width: 130,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT번호",
        width: 130,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 130,
      },
      {
        id: "col_bf_qty",
        field: "bf_qty",
        caption: "LOT수량",
        width: 130,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 130,
      },
      {
        id: "col_bnatur",
        field: "bnatur",
        caption: "재질",
        width: 130,
      },
      {
        id: "col_ordtype",
        field: "ordtype",
        caption: "수주형태",
        width: 130,
      },
      {
        id: "col_ordsts",
        field: "ordsts",
        caption: "수주상태",
        width: 130,
      },
      {
        id: "col_project",
        field: "project",
        caption: "프로젝트",
        width: 130,
      },
      {
        id: "col_person",
        field: "person",
        caption: "담당자",
        width: 130,
      },
      {
        id: "col_dptcd",
        field: "dptcd",
        caption: "부서코드",
        width: 130,
      },
      {
        id: "col_poregnum",
        field: "poregnum",
        caption: "PO번호",
        width: 130,
      },
      {
        id: "col_amtunit",
        field: "amtunit",
        caption: "화폐단위",
        width: 130,
      },
      {
        id: "col_baseamt",
        field: "baseamt",
        caption: "기준금액",
        width: 130,
      },
      {
        id: "col_wonchgrat",
        field: "wonchgrat",
        caption: "원화환율",
        width: 130,
      },
      {
        id: "col_uschgrat",
        field: "uschgrat",
        caption: "대미환율",
        width: 130,
      },
      {
        id: "col_unp",
        field: "unp",
        caption: "단가",
        width: 130,
      },
      {
        id: "col_wonamt",
        field: "wonamt",
        caption: "원화금액",
        width: 130,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "세액",
        width: 130,
      },
      {
        id: "col_amt",
        field: "amt",
        caption: "금액",
        width: 130,
      },
      {
        id: "col_dlramt",
        field: "dlramt",
        caption: "달러금액",
        width: 130,
      },
      {
        id: "col_fiels",
        field: "fiels",
        caption: "첨부파일",
        width: 130,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 130,
      },
      {
        id: "col_ordkey",
        field: "ordkey",
        caption: "수주번호",
        width: 130,
      },
      {
        id: "col_plandt",
        field: "plandt",
        caption: "계획일자",
        width: 130,
      },
      {
        id: "col_planqty",
        field: "planqty",
        caption: "잔량",
        width: 130,
      },
      {
        id: "col_finyn",
        field: "finyn",
        caption: "완료여부",
        width: 130,
      },
      {
        id: "col_outdt",
        field: "outdt",
        caption: "출하일자",
        width: 130,
      },
      {
        id: "col_indt",
        field: "indt",
        caption: "입고일자",
        width: 130,
      },
      {
        id: "col_doexdiv",
        field: "doexdiv",
        caption: "내수구분",
        width: 130,
      },
      {
        id: "col_ordyn",
        field: "ordyn",
        caption: "수주완료여부",
        width: 130,
      },
      {
        id: "col_itemno",
        field: "itemno",
        caption: "품번",
        width: 130,
      },
    ],
  },
  {
    gridName: "grdPlanList",
    columns: [
      {
        id: "col_plandt_p",
        field: "plandt",
        caption: "계획일자",
        width: 120,
      },
      {
        id: "col_finexpdt_p",
        field: "finexpdt",
        caption: "완료예정일",
        width: 120,
      },
      {
        id: "col_proccd_p",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_procseq_p",
        field: "procseq",
        caption: "공정순서",
        width: 120,
      },
      {
        id: "col_outprocyn_p",
        field: "outprocyn",
        caption: "외주구분",
        width: 120,
      },
      {
        id: "col_itemcd_p",
        field: "itemcd",
        caption: "재공품코드",
        width: 120,
      },
      {
        id: "col_qty_p",
        field: "qty",
        caption: "수량",
        width: 130,
      },
      {
        id: "col_procqty_p",
        field: "procqty",
        caption: "재공생산량",
        width: 130,
      },
      {
        id: "col_qtyunit_p",
        field: "qtyunit",
        caption: "수량단위",
        width: 130,
      },
      {
        id: "col_insiz_p",
        field: "insiz",
        caption: "규격",
        width: 130,
      },
      {
        id: "col_prodmac_p",
        field: "prodmac",
        caption: "설비",
        width: 130,
      },
      {
        id: "col_prodemp_p",
        field: "prodemp",
        caption: "작업자",
        width: 130,
      },
      {
        id: "col_plankey_p",
        field: "plankey",
        caption: "생산계획번호",
        width: 130,
      },
      {
        id: "col_ordkey_p",
        field: "ordkey",
        caption: "수주번호",
        width: 130,
      },
      {
        id: "col_poregnum_p",
        field: "poregnum",
        caption: "PO번호",
        width: 130,
      },
      {
        id: "col_purtype_p",
        field: "purtype",
        caption: "발주유형",
        width: 130,
      },
      {
        id: "col_itemnm_p",
        field: "itemnm",
        caption: "품목명",
        width: 130,
      },
      {
        id: "col_itemlvl1_p",
        field: "itemlvl1",
        caption: "대분류",
        width: 130,
      },
      {
        id: "col_itemlvl2_p",
        field: "itemlvl2",
        caption: "중분류",
        width: 130,
      },
      {
        id: "col_itemlvl3_p",
        field: "itemlvl3",
        caption: "소분류",
        width: 130,
      },
      {
        id: "col_urgencyyn_p",
        field: "urgencyyn",
        caption: "긴급여부",
        width: 130,
      },

      {
        id: "col_custnm_p",
        field: "custnm",
        caption: "업체명",
        width: 130,
      },
      {
        id: "col_remark_p",
        field: "remark",
        caption: "비고",
        width: 130,
      },
    ],
  },
  {
    gridName: "grdMtrList",
    columns: [
      {
        id: "col_proccd_m",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_chlditemcd_m",
        field: "chlditemcd",
        caption: "소요자재코드",
        width: 120,
      },
      {
        id: "col_chlditemnm_m",
        field: "chlditemnm",
        caption: "소요자재명",
        width: 120,
      },
      {
        id: "col_procqty_m",
        field: "procqty",
        caption: "재공생산량",
        width: 120,
      },
      {
        id: "col_unitqty_m",
        field: "unitqty",
        caption: "소요량",
        width: 120,
      },
      {
        id: "col_qtyunit_m",
        field: "qtyunit",
        caption: "수량단위",
        width: 120,
      },
      {
        id: "col_outgb_m",
        field: "outgb",
        caption: "자재사용구분",
        width: 120,
      },
    ],
  },
];
