import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_attyn",
        field: "attyn",
        caption: "도면여부",
        width: 100,
      },
      {
        id: "col_plandt",
        field: "plandt",
        caption: "계획일자",
        width: 120,
      },
      {
        id: "col_finexpdt",
        field: "finexpdt",
        caption: "완료예정일",
        width: 120,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_reqty",
        field: "reqty",
        caption: "지시량",
        width: 100,
      },
      {
        id: "col_finyn",
        field: "finyn",
        caption: "완료여부",
        width: 100,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_planno",
        field: "planno",
        caption: "생산계획번호",
        width: 150,
      },
      {
        id: "col_ordnum",
        field: "ordnum",
        caption: "수주번호",
        width: 150,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_plqty",
        field: "plqty",
        caption: "계획수량",
        width: 100,
      },
      {
        id: "col_bnatur",
        field: "bnatur",
        caption: "재질",
        width: 100,
      },
      {
        id: "col_attdatnum",
        field: "attdatnum",
        caption: "첨부파일",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_godt",
        field: "godt",
        caption: "지시일자",
        width: 120,
      },
      {
        id: "col_reqty2",
        field: "reqty",
        caption: "지시량",
        width: 100,
      },
      {
        id: "col_proccd",
        field: "proccd",
        caption: "공정",
        width: 100,
      },
      {
        id: "col_procseq",
        field: "procseq",
        caption: "공정순서",
        width: 100,
      },
      {
        id: "col_prodmac",
        field: "prodmac",
        caption: "설비",
        width: 100,
      },
      {
        id: "col_prodemp",
        field: "prodemp",
        caption: "작업자",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_godt2",
        field: "godt",
        caption: "지시일자",
        width: 120,
      },
      {
        id: "col_itemcd2",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm2",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz2",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_proccd2",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_procseq2",
        field: "procseq",
        caption: "공정순서",
        width: 100,
      },
      {
        id: "col_prodemp2",
        field: "prodemp",
        caption: "작업자",
        width: 120,
      },
      {
        id: "col_prodmac2",
        field: "prodmac",
        caption: "설비",
        width: 120,
      },
      {
        id: "col_qty2",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_prodqty",
        field: "prodqty",
        caption: "생산수량",
        width: 100,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "수량단위",
        width: 120,
      },
      {
        id: "col_finyn2",
        field: "finyn",
        caption: "완료여부",
        width: 100,
      },
      {
        id: "col_gokey",
        field: "gokey",
        caption: "작업지시번호",
        width: 150,
      },
      {
        id: "col_QD9yn",
        field: "QD9yn",
        caption: "QD9yn",
        width: 80,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_finexpdt2",
        field: "finexpdt",
        caption: "완료예정일",
        width: 120,
      },
      {
        id: "col_godt3",
        field: "godt",
        caption: "지시일자",
        width: 120,
      },
      {
        id: "col_custnm2",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_project",
        field: "project",
        caption: "공사명",
        width: 100,
      },
      {
        id: "col_prodmac3",
        field: "prodmac",
        caption: "설비",
        width: 100,
      },
      {
        id: "col_prodemp3",
        field: "prodemp",
        caption: "작업자",
        width: 120,
      },
      {
        id: "col_proccd3",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_procseq3",
        field: "procseq",
        caption: "공정순서",
        width: 100,
      },
      {
        id: "col_itemnm3",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_jisiqty",
        field: "jisiqty",
        caption: "지시수량",
        width: 100,
      },
      {
        id: "col_goodqty",
        field: "goodqty",
        caption: "양품수량",
        width: 100,
      },
      {
        id: "col_badqty",
        field: "badqty",
        caption: "불량수량",
        width: 100,
      },
      {
        id: "col_tot_jisiqty",
        field: "tot_jisiqty",
        caption: "누적지시량",
        width: 100,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 120,
      },
      {
        id: "col_location",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_plandt2",
        field: "plandt",
        caption: "계획일자",
        width: 120,
      },
      {
        id: "col_planqty",
        field: "planqty",
        caption: "계획수량",
        width: 100,
      },
      {
        id: "col_gokey2",
        field: "gokey",
        caption: "작업지시번호",
        width: 150,
      },
      {
        id: "col_finyn3",
        field: "finyn",
        caption: "완료여부",
        width: 100,
      },
      {
        id: "col_itemno",
        field: "itemno",
        caption: "품번",
        width: 120,
      },
    ],
  },
];
