import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_gubun",
        field: "gubun",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_indt",
        field: "indt",
        caption: "입고일자",
        width: 120,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 150,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_outqty",
        field: "outqty",
        caption: "불출량",
        width: 100,
      },
      {
        id: "col_useqty",
        field: "useqty",
        caption: "사용량",
        width: 100,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "수량단위",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "입고업체명",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_proddt",
        field: "proddt",
        caption: "생산일자",
        width: 120,
      },
      {
        id: "col_rekey",
        field: "rekey",
        caption: "생산번호",
        width: 150,
      },
      {
        id: "col_prodemp",
        field: "prodemp",
        caption: "작업자",
        width: 120,
      },
      {
        id: "col_proccd",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_itemcd2",
        field: "itemcd",
        caption: "제공품코드",
        width: 150,
      },
      {
        id: "col_itemnm2",
        field: "itemnm",
        caption: "제공품명",
        width: 150,
      },
      {
        id: "col_insiz2",
        field: "insiz",
        caption: "제공품규격",
        width: 120,
      },
      {
        id: "col_lotnum2",
        field: "lotnum",
        caption: "생산LOT",
        width: 120,
      },
      {
        id: "col_goodqty",
        field: "goodqty",
        caption: "양품수량",
        width: 100,
      },
      {
        id: "col_badqty",
        field: "badqty",
        caption: "불량수량",
        width: 100,
      },
      {
        id: "col_inproccd",
        field: "inproccd",
        caption: "투입품공정",
        width: 120,
      },
      {
        id: "col_inqty",
        field: "inqty",
        caption: "투입량",
        width: 100,
      },
      {
        id: "col_initemcd",
        field: "initemcd",
        caption: "투입품코드",
        width: 150,
      },
      {
        id: "col_initemnm",
        field: "initemnm",
        caption: "투입품명",
        width: 150,
      },
      {
        id: "col_usetype",
        field: "usetype",
        caption: "투입경로",
        width: 120,
      },
      {
        id: "col_procseq",
        field: "procseq",
        caption: "공정순서",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_outdt",
        field: "outdt",
        caption: "불출일자",
        width: 120,
      },
      {
        id: "col_lotnum3",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_itemcd3",
        field: "itemcd",
        caption: "품목코드",
        width: 150,
      },
      {
        id: "col_itemnm3",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz3",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_user_name",
        field: "user_name",
        caption: "사용자명",
        width: 120,
      },
      {
        id: "col_qty3",
        field: "qty",
        caption: "수량",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_indt2",
        field: "indt",
        caption: "입고일자",
        width: 120,
      },
      {
        id: "col_gubun2",
        field: "gubun",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_itemcd4",
        field: "itemcd",
        caption: "품목코드",
        width: 150,
      },
      {
        id: "col_itemnm4",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz4",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_lotnum4",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_inqty2",
        field: "inqty",
        caption: "입고량",
        width: 100,
      },
      {
        id: "col_outqty2",
        field: "outqty",
        caption: "출고량",
        width: 100,
      },
      {
        id: "col_custnm2",
        field: "custnm",
        caption: "업체명",
        width: 150,
      },
    ],
  },
];
