import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_pgmdiv",
        field: "pgmdiv",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_qcdt",
        field: "qcdt",
        caption: "검사일자",
        width: 120,
      },
      {
        id: "col_strtime",
        field: "strtime",
        caption: "측정시작시간",
        width: 150,
      },
      {
        id: "col_endtime",
        field: "endtime",
        caption: "측정종료시간",
        width: 150,
      },
      {
        id: "col_qctime",
        field: "qctime",
        caption: "소요시간",
        width: 100,
      },
      {
        id: "col_qcno",
        field: "qcno",
        caption: "검사차수",
        width: 100,
      },
      {
        id: "col_qcperson",
        field: "qcperson",
        caption: "검사자",
        width: 100,
      },
      {
        id: "col_qcdecision",
        field: "qcdecision",
        caption: "판정",
        width: 100,
      },
      {
        id: "col_prodemp",
        field: "prodemp",
        caption: "작업자",
        width: 100,
      },
      {
        id: "col_proccd",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 120,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_inspeccd",
        field: "inspeccd",
        caption: "검사항목",
        width: 120,
      },
      {
        id: "col_qc_spec",
        field: "qc_spec",
        caption: "측정기준명",
        width: 150,
      },
      {
        id: "col_qcvalue1",
        field: "qcvalue1",
        caption: "측정값",
        width: 100,
      },
      {
        id: "col_qcresult1",
        field: "qcresult1",
        caption: "측정결과",
        width: 120,
      },
      {
        id: "col_qckey",
        field: "qckey",
        caption: "검사실적번호",
        width: 150,
      },
      {
        id: "col_rekey",
        field: "rekey",
        caption: "생산실적번호",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_div",
        field: "div",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_proddt",
        field: "proddt",
        caption: "생산일자",
        width: 120,
      },
      {
        id: "col_proccd2",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_person",
        field: "person",
        caption: "검사자",
        width: 100,
      },
      {
        id: "col_qcdecision2",
        field: "qcdecision",
        caption: "판정",
        width: 100,
      },
      {
        id: "col_prodemp2",
        field: "prodemp",
        caption: "작업자",
        width: 100,
      },
      {
        id: "col_itemcd2",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm2",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz2",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_lotnum2",
        field: "lotnum",
        caption: "LOT NO",
        width: 120,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_rekey2",
        field: "rekey",
        caption: "생산실적번호",
        width: 150,
      },
      {
        id: "col_plankey",
        field: "plankey",
        caption: "생산계획번호",
        width: 150,
      },
      {
        id: "col_qcnum",
        field: "qcnum",
        caption: "검사실적번호",
        width: 150,
      },
      {
        id: "col_stdnum",
        field: "stdnum",
        caption: "검사표준번호",
        width: 150,
      },
      {
        id: "col_stdrev",
        field: "stdrev",
        caption: "검사표준리비전",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_차수",
        field: "차수",
        caption: "차수",
        width: 120,
      },
      {
        id: "col_검사일자",
        field: "검사일자",
        caption: "검사일자",
        width: 120,
      },
      {
        id: "col_측정시작시간",
        field: "측정시작시간",
        caption: "측정시작시간",
        width: 150,
      },
      {
        id: "col_측정종료시간",
        field: "측정종료시간",
        caption: "측정종료시간",
        width: 150,
      },
      {
        id: "col_측정소요시간",
        field: "측정소요시간",
        caption: "측정소요시간",
        width: 120,
      },
      {
        id: "col_검사자",
        field: "검사자",
        caption: "검사자",
        width: 100,
      },
      {
        id: "col_외경",
        field: "외경",
        caption: "외경",
        width: 120,
      },
      {
        id: "col_비고",
        field: "비고",
        caption: "비고",
        width: 250,
      },
      {
        id: "col_검사실적번호",
        field: "검사실적번호",
        caption: "검사실적번호",
        width: 150,
      },
    ],
  },
];
