import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_indt",
        field: "indt",
        caption: "입고일자",
        width: 120,
      },
      {
        id: "col_inkey",
        field: "inkey",
        caption: "입고번호",
        width: 150,
      },
      {
        id: "col_proccd",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계정",
        width: 120,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "수량단위",
        width: 120,
      },
      {
        id: "col_proddt",
        field: "proddt",
        caption: "생산일자",
        width: 150,
      },
      {
        id: "col_rekey",
        field: "rekey",
        caption: "생산실적번호",
        width: 150,
      },
      {
        id: "col_ordkey",
        field: "ordkey",
        caption: "수주번호",
        width: 150,
      },
      {
        id: "col_plankey",
        field: "plankey",
        caption: "생산계획번호",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_outdt",
        field: "outdt",
        caption: "매출일자",
        width: 120,
      },
      {
        id: "col_person",
        field: "person",
        caption: "담당자",
        width: 120,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 150,
      },
      {
        id: "col_lotnum2",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_itemcd2",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm2",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz2",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_itemacnt2",
        field: "itemacnt",
        caption: "품목계정",
        width: 120,
      },
      {
        id: "col_qty2",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_qtyunit2",
        field: "qtyunit",
        caption: "수량단위",
        width: 120,
      },
      {
        id: "col_location",
        field: "location",
        caption: "사업장",
        width: 120,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_proddt3",
        field: "proddt",
        caption: "생산일자",
        width: 120,
      },
      {
        id: "col_rekey3",
        field: "rekey",
        caption: "생산실적번호",
        width: 150,
      },
      {
        id: "col_location3",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_prodemp",
        field: "prodemp",
        caption: "작업자",
        width: 120,
      },
      {
        id: "col_proccd3",
        field: "proccd",
        caption: "공정",
        width: 120,
      },
      {
        id: "col_procseq",
        field: "procseq",
        caption: "공정순서",
        width: 100,
      },
      {
        id: "col_itemcd3",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm3",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz3",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_lotnum3",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_qty3",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_badqty3",
        field: "badqty",
        caption: "불량수량",
        width: 100,
      },
      {
        id: "col_inproccd",
        field: "inproccd",
        caption: "투입공정",
        width: 120,
      },
      {
        id: "col_inlot",
        field: "inlot",
        caption: "투입LOT",
        width: 150,
      },
      {
        id: "col_inqty",
        field: "inqty",
        caption: "투입량",
        width: 100,
      },
      {
        id: "col_initemcd",
        field: "initemcd",
        caption: "투입품코드",
        width: 120,
      },
      {
        id: "col_initemnm",
        field: "initemnm",
        caption: "투입품명",
        width: 150,
      },
      {
        id: "col_usetype",
        field: "usetype",
        caption: "투입경로",
        width: 120,
      },
      {
        id: "col_berekey",
        field: "berekey",
        caption: "투입번호",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_indt4",
        field: "indt",
        caption: "입고일자",
        width: 120,
      },
      {
        id: "col_gubun",
        field: "gubun",
        caption: "구분",
        width: 120,
      },
      {
        id: "col_location4",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_custcd4",
        field: "custcd",
        caption: "업체코드",
        width: 120,
      },
      {
        id: "col_custnm4",
        field: "custnm",
        caption: "업체명",
        width: 150,
      },
      {
        id: "col_itemcd4",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm4",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz4",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_lotnum4",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_inqty4",
        field: "inqty",
        caption: "입고수량",
        width: 100,
      },
      {
        id: "col_heatno",
        field: "heatno",
        caption: "HEAT NO",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList5",
    columns: [
      {
        id: "col_outdt5",
        field: "outdt",
        caption: "매출일자",
        width: 120,
      },
      {
        id: "col_itemcd5",
        field: "itemcd",
        caption: "품목코드",
        width: 120,
      },
      {
        id: "col_itemnm5",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz5",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_lotnum5",
        field: "lotnum",
        caption: "LOT NO",
        width: 150,
      },
      {
        id: "col_person5",
        field: "person",
        caption: "담당자",
        width: 120,
      },
      {
        id: "col_qty5",
        field: "qty",
        caption: "수량",
        width: 100,
      },
    ],
  },
];
