import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_orddt",
        field: "orddt",
        caption: "수주일자",
        width: 120,
      },
      {
        id: "col_dlvdt",
        field: "dlvdt",
        caption: "납기일자",
        width: 120,
      },
      {
        id: "col_ordnum",
        field: "ordnum",
        caption: "수주번호",
        width: 100,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 120,
      },
      {
        id: "col_ordsts",
        field: "ordsts",
        caption: "수주상태",
        width: 120,
      },
      {
        id: "col_doexdiv",
        field: "doexdiv",
        caption: "내수구분",
        width: 120,
      },
      {
        id: "col_taxdiv",
        field: "taxdiv",
        caption: "과세구분",
        width: 120,
      },
      {
        id: "col_out_qty",
        field: "out_qty",
        caption: "출하수량",
        width: 100,
      },
      {
        id: "col_sale_qty",
        field: "sale_qty",
        caption: "판매수량",
        width: 100,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수주수량",
        width: 100,
      },
      {
        id: "col_specialamt",
        field: "specialamt",
        caption: "발주금액",
        width: 100,
      },
      {
        id: "col_amt",
        field: "amt",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "세액",
        width: 100,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "합계금액",
        width: 100,
      },
      {
        id: "col_location",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_dptcd",
        field: "dptcd",
        caption: "부서",
        width: 120,
      },
      {
        id: "col_person",
        field: "person",
        caption: "담당자",
        width: 120,
      },
      {
        id: "col_quokey",
        field: "quokey",
        caption: "견적번호",
        width: 100,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 200,
      },
      {
        id: "col_finyn",
        field: "finyn",
        caption: "완료여부",
        width: 80,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 150,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계정",
        width: 120,
      },
      {
        id: "col_qty2",
        field: "qty",
        caption: "수주량",
        width: 100,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "단위",
        width: 100,
      },
      {
        id: "col_unp",
        field: "unp",
        caption: "단가",
        width: 100,
      },
      {
        id: "col_wonamt",
        field: "wonamt",
        caption: "금액",
        width: 100,
      },
      {
        id: "col_taxamt2",
        field: "taxamt",
        caption: "세액",
        width: 100,
      },
      {
        id: "col_totamt2",
        field: "totamt",
        caption: "합계금액",
        width: 100,
      },
      {
        id: "col_remark2",
        field: "remark",
        caption: "비고",
        width: 200,
      },
      {
        id: "col_purcustnm",
        field: "purcustnm",
        caption: "발주처",
        width: 120,
      },
      {
        id: "col_outqty",
        field: "outqty",
        caption: "출하수량",
        width: 100,
      },
      {
        id: "col_sale_qty2",
        field: "sale_qty",
        caption: "판매수량",
        width: 100,
      },
      {
        id: "col_finyn2",
        field: "finyn",
        caption: "완료여부",
        width: 100,
      },
      {
        id: "col_bf_qty",
        field: "bf_qty",
        caption: "LOT수량",
        width: 100,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 100,
      },
    ],
  },
];
