import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_billstat2",
        field: "billstat2",
        caption: "상태",
        width: 120,
      },
      {
        id: "col_report_stat",
        field: "report_stat",
        caption: "신고상태",
        width: 120,
      },
      {
        id: "col_reqnum",
        field: "reqnum",
        caption: "계산서번호",
        width: 150,
      },
      {
        id: "col_taxdt",
        field: "taxdt",
        caption: "계산서일자",
        width: 120,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 200,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_custregnum",
        field: "custregnum",
        caption: "사업자등록번호",
        width: 150,
      },
      {
        id: "col_splyamt",
        field: "splyamt",
        caption: "공급가액",
        width: 100,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "세액",
        width: 100,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "합계금액",
        width: 100,
      },
      {
        id: "col_colfinyn",
        field: "colfinyn",
        caption: "수금강제완료",
        width: 100,
      },
      {
        id: "col_payindt",
        field: "payindt",
        caption: "수금완료일",
        width: 120,
      },
      {
        id: "col_items",
        field: "items",
        caption: "거래품목",
        width: 150,
      },
      {
        id: "col_location",
        field: "location",
        caption: "사업장",
        width: 120,
      },
      {
        id: "col_taxtype",
        field: "taxtype",
        caption: "계산서유형",
        width: 120,
      },
      {
        id: "col_rtxisuyn",
        field: "rtxisuyn",
        caption: "역발행여부",
        width: 120,
      },
      {
        id: "col_etax",
        field: "etax",
        caption: "TAX구분",
        width: 120,
      },
      {
        id: "col_actkey",
        field: "actkey",
        caption: "매출전표",
        width: 150,
      },
      {
        id: "col_collectnum",
        field: "collectnum",
        caption: "수금",
        width: 150,
      },
      {
        id: "col_collectamt",
        field: "collectamt",
        caption: "수금금액",
        width: 100,
      },
      {
        id: "col_report_issue_id",
        field: "report_issue_id",
        caption: "세금계산서 승인번호",
        width: 200,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_recnum",
        field: "recnum",
        caption: "판매번호",
        width: 150,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 150,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 120,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계정",
        width: 120,
      },
      {
        id: "col_qty2",
        field: "qty",
        caption: "수량",
        width: 100,
      },
      {
        id: "col_wonamt2",
        field: "wonamt",
        caption: "원화금액",
        width: 100,
      },
      {
        id: "col_taxamt2",
        field: "taxamt",
        caption: "세액",
        width: 100,
      },
      {
        id: "col_totamt2",
        field: "totamt",
        caption: "합계금액",
        width: 100,
      },
    ],
  },
  {
    gridName: "grdList3",
    columns: [
      {
        id: "col_acntdt",
        field: "acntdt",
        caption: "전표일자",
        width: 120,
      },
      {
        id: "col_acseq2",
        field: "acseq2",
        caption: "전표순번",
        width: 100,
      },
      {
        id: "col_drcrdiv",
        field: "drcrdiv",
        caption: "차대구분",
        width: 200,
      },
      {
        id: "col_acntcd",
        field: "acntcd",
        caption: "계정코드",
        width: 150,
      },
      {
        id: "col_acntnm",
        field: "acntnm",
        caption: "계정명",
        width: 150,
      },
      {
        id: "col_slipamt_1",
        field: "slipamt_1",
        caption: "차변금액",
        width: 100,
      },
      {
        id: "col_slipamt_2",
        field: "slipamt_2",
        caption: "대변금액",
        width: 100,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 200,
      },
      {
        id: "col_ackey",
        field: "ackey",
        caption: "전표번호",
        width: 150,
      },
    ],
  },
  {
    gridName: "grdList4",
    columns: [
      {
        id: "col_indt",
        field: "indt",
        caption: "수금일자",
        width: 120,
      },
      {
        id: "col_drcrdiv4",
        field: "drcrdiv",
        caption: "차대구분",
        width: 200,
      },
      {
        id: "col_acntcd4",
        field: "acntcd",
        caption: "계정코드",
        width: 150,
      },
      {
        id: "col_acntnm4",
        field: "acntnm",
        caption: "계정명",
        width: 150,
      },
      {
        id: "col_amt_1",
        field: "amt_1",
        caption: "차변금액",
        width: 100,
      },
      {
        id: "col_amt_2",
        field: "amt_2",
        caption: "대변금액",
        width: 100,
      },
      {
        id: "col_acntnum",
        field: "acntnum",
        caption: "계좌번호",
        width: 120,
      },
      {
        id: "col_remark4",
        field: "remark",
        caption: "비고",
        width: 200,
      },
      {
        id: "col_collactkey",
        field: "collactkey",
        caption: "수금번호",
        width: 150,
      },
    ],
  },
];
