import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_outdt",
        field: "outdt",
        caption: "매출일자",
        width: 150,
      },
      {
        id: "col_shipdt",
        field: "shipdt",
        caption: "선적일자",
        width: 150,
      },
      {
        id: "col_person",
        field: "person",
        caption: "담당자",
        width: 150,
      },
      {
        id: "col_custcd",
        field: "custcd",
        caption: "업체코드",
        width: 200,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 250,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수량",
        width: 150,
      },
      {
        id: "col_amt",
        field: "amt",
        caption: "금액",
        width: 150,
      },
      {
        id: "col_wonamt",
        field: "wonamt",
        caption: "원화금액",
        width: 150,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "세액",
        width: 150,
      },
      {
        id: "col_totamt",
        field: "totamt",
        caption: "합계금액",
        width: 150,
      },
      {
        id: "col_taxnum",
        field: "taxnum",
        caption: "계산서NO",
        width: 250,
      },
      {
        id: "col_reckey",
        field: "reckey",
        caption: "판매번호",
        width: 250,
      },
    ],
  },
  {
    gridName: "grdList2",
    columns: [
      {
        id: "col_sort_seq",
        field: "sort_seq",
        caption: "정렬순서",
        width: 80,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 250,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 200,
      },
      {
        id: "col_itemacnt",
        field: "itemacnt",
        caption: "품목계정",
        width: 150,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 200,
      },
      {
        id: "col_qty2",
        field: "qty",
        caption: "수량",
        width: 120,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "수량단위",
        width: 150,
      },
      {
        id: "col_unpcalmeth",
        field: "unpcalmeth",
        caption: "단가산정방법",
        width: 150,
      },
      {
        id: "col_unp",
        field: "unp",
        caption: "단가",
        width: 120,
      },
      {
        id: "col_amt2",
        field: "amt",
        caption: "금액",
        width: 120,
      },
      {
        id: "col_wonamt2",
        field: "wonamt",
        caption: "원화금액",
        width: 120,
      },
      {
        id: "col_taxamt2",
        field: "taxamt",
        caption: "세액",
        width: 120,
      },
      {
        id: "col_totamt2",
        field: "totamt",
        caption: "합계금액",
        width: 120,
      },
      {
        id: "col_dlramt",
        field: "dlramt",
        caption: "달러금액",
        width: 120,
      },
      {
        id: "col_unitwgt",
        field: "unitwgt",
        caption: "단량",
        width: 120,
      },
      {
        id: "col_totwgt",
        field: "totwgt",
        caption: "총중량",
        width: 120,
      },
      {
        id: "col_wgtunit",
        field: "wgtunit",
        caption: "중량단위",
        width: 120,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 400,
      },
      {
        id: "col_poregnum",
        field: "poregnum",
        caption: "PO사업자",
        width: 250,
      },
      {
        id: "col_ordkey",
        field: "ordkey",
        caption: "수주번호",
        width: 250,
      },
      {
        id: "col_outreckey",
        field: "outreckey",
        caption: "출하번호",
        width: 250,
      },
      {
        id: "col_reckey2",
        field: "reckey",
        caption: "판매번호",
        width: 250,
      },
    ],
  },
];
