import { TGrid } from "../types";

export const gridList: Array<TGrid> = [
  {
    gridName: "grdList",
    columns: [
      {
        id: "col_dlvdt",
        field: "dlvdt",
        caption: "납기일자",
        width: 100,
      },
      {
        id: "col_orddt",
        field: "orddt",
        caption: "수주일자",
        width: 100,
      },
      {
        id: "col_dptcd",
        field: "dptcd",
        caption: "담당부서",
        width: 100,
      },
      {
        id: "col_person",
        field: "person",
        caption: "수주담당자",
        width: 100,
      },
      {
        id: "col_custnm",
        field: "custnm",
        caption: "업체명",
        width: 170,
      },
      {
        id: "col_itemcd",
        field: "itemcd",
        caption: "품목코드",
        width: 250,
      },
      {
        id: "col_itemnm",
        field: "itemnm",
        caption: "품목명",
        width: 170,
      },
      {
        id: "col_insiz",
        field: "insiz",
        caption: "규격",
        width: 170,
      },
      {
        id: "col_itemlvl1",
        field: "itemlvl1",
        caption: "대분류",
        width: 100,
      },
      {
        id: "col_itemlvl2",
        field: "itemlvl2",
        caption: "중분류",
        width: 100,
      },
      {
        id: "col_itemlvl3",
        field: "itemlvl3",
        caption: "소분류",
        width: 100,
      },
      {
        id: "col_qty",
        field: "qty",
        caption: "수주수량",
        width: 120,
      },
      {
        id: "col_outqty",
        field: "outqty",
        caption: "출하량",
        width: 120,
      },
      {
        id: "col_reqty",
        field: "reqty",
        caption: "수주잔량",
        width: 120,
      },
      {
        id: "col_saleqty",
        field: "saleqty",
        caption: "판매수량",
        width: 120,
      },
      {
        id: "col_qtyunit",
        field: "qtyunit",
        caption: "단위",
        width: 120,
      },
      {
        id: "col_unp",
        field: "unp",
        caption: "단가",
        width: 120,
      },
      {
        id: "col_amtunit",
        field: "amtunit",
        caption: "화폐단위",
        width: 120,
      },
      {
        id: "col_amt",
        field: "amt",
        caption: "원화금액",
        width: 120,
      },
      {
        id: "col_wonamt",
        field: "wonamt",
        caption: "원화금액",
        width: 120,
      },
      {
        id: "col_taxamt",
        field: "taxamt",
        caption: "세액",
        width: 120,
      },
      {
        id: "col_dlramt",
        field: "dlramt",
        caption: "외화단가",
        width: 120,
      },
      {
        id: "col_ordnum",
        field: "ordnum",
        caption: "수주번호",
        width: 170,
      },
      {
        id: "col_lotnum",
        field: "lotnum",
        caption: "LOT NO",
        width: 120,
      },
      {
        id: "col_remark",
        field: "remark",
        caption: "비고",
        width: 120,
      },
      {
        id: "col_ordsts",
        field: "ordsts",
        caption: "수주상태",
        width: 120,
      },
      {
        id: "col_finyn",
        field: "finyn",
        caption: "수주완료여부",
        width: 120,
      },
      {
        id: "col_poregnum",
        field: "poregnum",
        caption: "PO번호",
        width: 120,
      },
      {
        id: "col_project",
        field: "project",
        caption: "프로젝트",
        width: 120,
      },
      {
        id: "col_rcvcustnm",
        field: "rcvcustnm",
        caption: "인수처명",
        width: 170,
      },
      {
        id: "col_playn",
        field: "playn",
        caption: "계획",
        width: 120,
      },
    ],
  },
];
